name: SHOPSMART CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ---------- CLIENT ----------
      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build client
        working-directory: client
        run: npm run build

      # ---------- SERVER ----------
      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Server build (if any)
        working-directory: server
        run: echo "No build step"
